# LCM - Transportation Problem

In [ ]:
def least_cost_method(supply, demand, costs):
    """
    Calculates the Least Cost Method for solving the Transportation Problem.

    Parameters:
        supply (list): A list of supply values for each source.
        demand (list): A list of demand values for each destination.
        costs (list): A 2D list of transportation costs for each source-destination pair.

    Returns:
        (list, float): A tuple containing the solution matrix and the total cost.
    """
    # Initialize the solution matrix with zeros
    rows = len(supply)
    cols = len(demand)
    solution = [[0 for j in range(cols)] for i in range(rows)]

    # While there is still supply and demand to be satisfied
    while sum(supply) > 0 and sum(demand) > 0:
        # Find the cell with the minimum cost
        min_cost = float('inf')
        min_i, min_j = -1, -1
        for i in range(rows):
            for j in range(cols):
                if supply[i] > 0 and demand[j] > 0 and costs[i][j] < min_cost:
                    min_cost = costs[i][j]
                    min_i, min_j = i, j

        # Calculate the amount to be transported
        amount = min(supply[min_i], demand[min_j])

        # Update the solution matrix and the supply/demand lists
        solution[min_i][min_j] = amount
        supply[min_i] -= amount
        demand[min_j] -= amount

    # Calculate the total cost of the solution
    total_cost = sum([solution[i][j] * costs[i][j] for i in range(rows) for j in range(cols)])

    return solution, total_cost


**An example**

In [ ]:
# Example input data
supply = [40, 60, 50]
demand = [20, 30, 50, 50]
costs = [
    [4, 6, 8, 8],
    [6, 8, 6, 7],
    [5, 7, 6, 8],
]

# Calculate the solution using the Least Cost Method
solution, total_cost = least_cost_method(supply, demand, costs)

# Print the solution matrix and the total cost
print("Solution Matrix:")
for row in solution:
    print(row)
print("Total Cost:", total_cost)


Solution Matrix:
[20, 20, 0, 0]
[0, 0, 50, 10]
[0, 10, 0, 40]
Total Cost: 960


**The manual method for reference:**
https://youtu.be/5xCUzCTjAXQ

In [ ]:
def least_cost_method2(supply, demand, costs):
    """
    Calculates the Least Cost Method for solving the Transportation Problem.

    Parameters:
        supply (list): A list of supply values for each source.
        demand (list): A list of demand values for each destination.
        costs (list): A 2D list of transportation costs for each source-destination pair.

    Returns:
        (list, float): A tuple containing the solution matrix and the total cost.
    """
    # Calculate the total supply and demand
    total_supply = sum(supply)
    total_demand = sum(demand)

    # If the total supply is greater than the total demand, add a dummy column to the costs matrix
    if total_supply > total_demand:
        diff = total_supply - total_demand
        for i in range(len(costs)):
            costs[i].append(0)
        demand.append(diff)

    # If the total demand is greater than the total supply, add a dummy row to the costs matrix
    elif total_demand > total_supply:
        diff = total_demand - total_supply
        costs.append([0] * len(demand))
        supply.append(diff)

    # Initialize the solution matrix with zeros
    rows = len(supply)
    cols = len(demand)
    solution = [[0 for j in range(cols)] for i in range(rows)]

    # While there is still supply and demand to be satisfied
    while sum(supply) > 0 and sum(demand) > 0:
        # Find the cell with the minimum cost
        min_cost = float('inf')
        row_index, col_index = -1, -1
        for i in range(rows):
            for j in range(cols):
                if supply[i] > 0 and demand[j] > 0 and costs[i][j] < min_cost:
                    min_cost = costs[i][j]
                    row_index, col_index = i, j

        # Calculate the quantity to be transported
        quantity = min(supply[row_index], demand[col_index])

        # Update the solution matrix and the supply/demand lists
        solution[row_index][col_index] = quantity
        supply[row_index] -= quantity
        demand[col_index] -= quantity

    # Calculate the total cost
    total_cost = 0
    for i in range(rows):
        for j in range(cols):
            total_cost += solution[i][j] * costs[i][j]

    return solution, total_cost

In [ ]:
# Example input data
supply = [30, 10, 15, 5]
demand = [10, 15, 17, 10]
costs = [
    [3, 8, 9, 15],
    [2, 3, 8, 7],
    [6, 9, 7, 7],
    [2, 1, 1, 9]
]

# Calculate the solution using the Least Cost Method
solution, total_cost = least_cost_method2(supply, demand, costs)

# Print the solution matrix and the total cost
print("Solution Matrix:")
for row in solution:
    print(row)
print("Total Cost:", total_cost)


Solution Matrix:
[0, 10, 2, 10, 8]
[10, 0, 0, 0, 0]
[0, 0, 15, 0, 0]
[0, 5, 0, 0, 0]
Total Cost: 378


In [ ]:
#GGGGG




The manual method for reference: https://youtu.be/0R8YLbvksiI

# NWC - Transportation Problem

In [ ]:
import numpy as np

def NWC(costs, supply, demand):
    """
    Solves the transportation problem using the North West Corner method.

    Args:
        costs (numpy.ndarray): An (m x n) array of transportation costs.
        supply (numpy.ndarray): A 1D array of supply values for each source.
        demand (numpy.ndarray): A 1D array of demand values for each destination.

    Returns:
        Tuple(numpy.ndarray, float): The first element is an (m x n) array of transportation
        quantities, and the second element is the total cost of transportation.
    """
    m, n = costs.shape
    allocation = np.zeros((m, n))
    i, j = 0, 0
    total_cost = 0
    while i < m and j < n:
        if supply[i] < demand[j]:
            allocation[i][j] = supply[i]
            total_cost += supply[i] * costs[i][j]
            demand[j] -= supply[i]
            i += 1
        else:
            allocation[i][j] = demand[j]
            total_cost += demand[j] * costs[i][j]
            supply[i] -= demand[j]
            j += 1
    return allocation, total_cost


In [ ]:
costs = np.array([[11, 13, 17, 14], [16, 18, 14, 10], [21, 24, 13, 10]])
supply = np.array([250, 300, 400])
demand = np.array([200, 225, 275, 250])
allocation, total_cost = NWC(costs, supply, demand)
print("Allocation:\n", allocation)
print("Total cost:", total_cost)


Allocation:
 [[200.  50.   0.   0.]
 [  0. 175. 125.   0.]
 [  0.   0. 150. 250.]]
Total cost: 12200


In [ ]:
costs = np.array([[7, 12, 1, 5, 9], [15, 3, 12, 6, 14], [8, 16, 10, 12, 7], [18, 8, 17, 11, 16]])
supply = np.array([12, 11, 14, 8])
demand = np.array([10, 11, 15, 5, 4])
allocation, total_cost = NWC(costs, supply, demand)
print("Allocation:\n", allocation)
print("Total cost:", total_cost)



#exo 2 de PAG

Allocation:
 [[10.  2.  0.  0.  0.]
 [ 0.  9.  2.  0.  0.]
 [ 0.  0. 13.  1.  0.]
 [ 0.  0.  0.  4.  4.]]
Total cost: 395


In [ ]:
# least cost method exo 2 de PAG

costs = [[7, 12, 1, 5, 9],
         [15, 3, 12, 6, 14],
         [8, 16, 10, 12, 7],
         [18, 8, 17, 11, 16]]
supply = [12, 11, 14, 8]
demand = [10, 11, 15, 5, 4]



# Calculate the solution using the Least Cost Method
solution, total_cost = least_cost_method(supply, demand, costs)

# Print the solution matrix and the total cost
print("Solution Matrix:")
for row in solution:
    print(row)
print("Total Cost:", total_cost)


Solution Matrix:
[0, 0, 12, 0, 0]
[0, 11, 0, 0, 0]
[10, 0, 0, 0, 4]
[0, 0, 3, 5, 0]
Total Cost: 259


edit the code so each dunction only gets a simple array. edit the second one.